### ISSUE TITLE
Failing to extract Mario Lost levels (WUP-FA9P)

### ISSUE THREAD

**Issue by Azidus** [wheatevo/wiiu-vc-extractor#34] opened 2018-10-20 19:33 UTC
Heres the output:

[WUP-FA9P rapport.txt](https://github.com/wheatevo/wiiu-vc-extractor/files/2498463/WUP-FA9P.rapport.txt)

**Comment by TBirdSoars** [comment] 2019-07-02 00:34
I've identified some of the causes for Lost Levels to fail:

1. The game is actually a Famicom Disk System game, which has a different header that leads to it not being identified as an NES rom.

2. Correcting the program to accept the header leads to a .nes file with the correct name. However, the header is corrupted when the program attempts to fix it.

3. The file is loaded with junk, being 30 times larger than a normal NES game and is not the correct filetype; the filetype must be .fds.

4. Either the VC title is edited or the extraction process is bugged, as numerous "00 00" hex values are strewn throughout the output file.

My fork seems to take care of 1 and 2, but 3 and 4 currently require a hex editor to fix.

**Comment by TBirdSoars** [comment] 2019-07-19 03:12
As of now, my fork does manage to properly extract Lost Levels:
https://github.com/TBirdSoars/wiiu-vc-extractor/releases/tag/0.5.2.1

It won't work with any other Famicom Disk System games, but it might be possible; I would need another FDS game to test, but I'm not sure if there are any others on the eShop.

**Comment by wheatevo** [comment] 2019-07-21 11:36
Fixed by #35

**Closed by wheatevo** 2019-07-21 11:36 UTC

**Comment by Azidus** [comment] 2019-07-22 16:50
I works now, great work!!  :D

The only other Disk system games that I am aware of are:
Clu-Clu land on the original animal crossing game - probably not same file format as WiiU VC.
Murasama Castle on 3DS
I have heard "Vs. Excite Bike" is on the US WiiU eShop, if anybody is interested in testing it out.

**Comment by TBirdSoars** [comment] 2019-07-22 17:05
Clu-Clu Land from AC is actually what helped me figure this out - while it's not the exact same type of file (Wii U being a compressed .rpx), both Clu Clu Land and Lost Levels are in .qd format, which retains the CRC data from the original game disks. Emulators, however, do not support that format. I might look into the others, but this _should_ support them.
