### ISSUE TITLE
[Enhancement] PC Engine/Turbografx-16 support

### ISSUE THREAD

**Issue by Zowayix** [wheatevo/wiiu-vc-extractor#31] opened 2018-05-16 05:57 UTC
This is most definitely not going to be an easy one, but it's the last remaining VC system to support (since N64 and DS VC ROMs are just there), so why not I guess.

I bought some game called Neutopia, had a bit of a look into it myself.

The actual ROM files seem to be in content/pceemu/pce.pkg, which doesn't seem to be in any format that I know of (first few bytes are DA 00 0C 00 A0), but has what appears to be filenames:  
pceconfig.bin
neutopia_jp.PCE
neutopia_en.PCE

I don't know if PCE games are supposed to have any kind of ROM header that I can look for, nor do I have the game outside of VC so I can't search for where the file would be that way either.

**Comment by Zowayix** [comment] 2018-05-16 09:57
Had a bit of a poke around. There are some people on the internets who claim that the ROM starts at 0xc7, but that's evidently not correct, as "CE" is at 0xc7 here (from neutopia_jp.PCE). But if I'm doing this correctly, it starts at 0xca, right after the filename terminated by a null character. 

I know via No-Intro's database that Neutopia is supposed to be 384 KiB long, so I extracted that amount into a new file. Right after that, we see 00 00 60 00 and then neutopia_en.PCE followed by a null char... on a whim, I extracted the next 384 KiB after that (which happens to line up with the end of the .pkg file).

I didn't notice the 00 00 60 00 before the neutopia_jp.PCE, perhaps it's byte-swapped and 60 00 00 00 = 0x00060000 = 393216 = the ROM length? So that'd help.

Anyway, the extracted files boot in Mednafen. Yay! Their checksums don't match up against No-Intro though, which indicates that either I did something horribly wrong, or they've been modified for VC (probable, but TCRF doesn't mention anything).

**Comment by wheatevo** [comment] 2019-07-21 13:55
Taking a look at this using Bomberman '93.

**Comment by wheatevo** [comment] 2019-07-21 15:07
For now just going to create a more generic extractor that will extract each file within the pkg file based on the headers and file lengths. After that, going to research how the CD-style pkg files can be recombined into a more standard format.

**Comment by wheatevo** [comment] 2019-07-22 01:58
@Zowayix This has now been added and is working for .pce titles as of 0.7.0. The Super CD titles (I think Lords of Thunder may be the only one released on VC in the west) are extracted as their bin and ogg contents but the necessary .cue file is not created. I was unable to create a .cue file that worked successfully with Retroarch. It was loaded by Retroarch, but the PC Engine Super CD loader itself produced a load error. I am unsure if this is due to some change in the VC rom vs. the actual title.

**Comment by wheatevo** [comment] 2019-07-22 02:24
It looks like the issue is that we need to decompress the .bin files into a readable format. This will require some more research since the only tool I could find that did something similar was tg16inject (which appears to be closed source).

**Comment by wheatevo** [comment] 2020-10-10 19:40
Closing this since TG16 support has been added.

**Closed by wheatevo** 2020-10-10 19:40 UTC
Labels: enhancement
